export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//Global errors
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const DISABLE_ERRORS = "DISABLE_ERRORS";

//Users
export const GET_USER_STATS = "GET_USER_STATS";
export const GET_QUOTA_STATS = "GET_QUOTA_STATS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const CHANGE_USER_EMAIL = "CHANGE_USER_EMAIL";

//File sharer
export const GET_SHARED_FILES = "GET_SHARED_FILES";
export const DELETE_LINK = "DELETE_LINK";
export const GET_LINK_DETAILS = "GET_LINK_DETAILS";
export const DELETE_FILE = "DELETE_FILE";
export const ADD_FILES = "ADD_FILES";
export const GET_USER_LINK_STATS = "GET_USER_LINK_STATS";
export const EDIT_LINK = "EDIT_LINK";
export const UPLOADER_ADD_FILE = "UPLOADER_ADD_FILE";
export const UPLOADER_REMOVE_FILE = "UPLOADER_REMOVE_FILE";
export const UPLOADER_SET_LIMIT_REACHED = "UPLOADER_SET_LIMIT_REACHED";
export const UPLOADER_RESET = "UPLOADER_RESET";
