export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_PASSWORD_SENT = "RESET_PASSWORD_SENT";
export const NEW_PASSWORD_SENT = "NEW_PASSWORD_SENT";

//Global errors
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const DISABLE_ERRORS = "DISABLE_ERRORS";

//Users
export const GET_USER_STATS = "GET_USER_STATS";

//File sharer
export const GET_SHARED_FILES = "GET_SHARED_FILES";
export const DELETE_LINK = "DELETE_LINK";
export const GET_LINK_DETAILS = "GET_LINK_DETAILS";
export const DELETE_FILE = "DELETE_FILE";
export const ADD_FILES = "ADD_FILES";
export const GET_USER_LINK_STATS = "GET_USER_LINK_STATS";
